from lxml import etree
from pykml.factory import KML_ElementMaker as KML
from pykml.factory import ATOM_ElementMaker as ATOM
from pykml.factory import GX_ElementMaker as GX

doc = KML.kml(
  KML.Document(
    KML.name('28_Manzanas_INV2016.shp'),
    KML.Schema(
      KML.SimpleField(
        KML.displayName('<b>CVEGEO</b>'),
        type="string",
        name="CVEGEO",
      ),
      KML.SimpleField(
        KML.displayName('<b>VIVTOT</b>'),
        type="string",
        name="VIVTOT",
      ),
      KML.SimpleField(
        KML.displayName('<b>TVIVHAB</b>'),
        type="string",
        name="TVIVHAB",
      ),
      KML.SimpleField(
        KML.displayName('<b>P_TVIVHAB</b>'),
        type="string",
        name="P_TVIVHAB",
      ),
      KML.SimpleField(
        KML.displayName('<b>TVIVPAR</b>'),
        type="string",
        name="TVIVPAR",
      ),
      KML.SimpleField(
        KML.displayName('<b>P_TVIVPAR</b>'),
        type="string",
        name="P_TVIVPAR",
      ),
      KML.SimpleField(
        KML.displayName('<b>TVIVPARHAB</b>'),
        type="string",
        name="TVIVPARHAB",
      ),
      KML.SimpleField(
        KML.displayName('<b>PVIVPARHAB</b>'),
        type="string",
        name="PVIVPARHAB",
      ),
      KML.SimpleField(
        KML.displayName('<b>VIVPAR_DES</b>'),
        type="string",
        name="VIVPAR_DES",
      ),
      KML.SimpleField(
        KML.displayName('<b>P_VIVPAR_D</b>'),
        type="string",
        name="P_VIVPAR_D",
      ),
      KML.SimpleField(
        KML.displayName('<b>VIVPAR_UT</b>'),
        type="string",
        name="VIVPAR_UT",
      ),
      KML.SimpleField(
        KML.displayName('<b>P_VIVPAR_U</b>'),
        type="string",
        name="P_VIVPAR_U",
      ),
      KML.SimpleField(
        KML.displayName('<b>VIVNOHAB</b>'),
        type="string",
        name="VIVNOHAB",
      ),
      KML.SimpleField(
        KML.displayName('<b>P_VIVNOHAB</b>'),
        type="string",
        name="P_VIVNOHAB",
      ),
      KML.SimpleField(
        KML.displayName('<b>VPH_PISODT</b>'),
        type="string",
        name="VPH_PISODT",
      ),
      KML.SimpleField(
        KML.displayName('<b>P_V_PISODT</b>'),
        type="string",
        name="P_V_PISODT",
      ),
      KML.SimpleField(
        KML.displayName('<b>VPH_C_ELEC</b>'),
        type="string",
        name="VPH_C_ELEC",
      ),
      KML.SimpleField(
        KML.displayName('<b>P_V_C_ELEC</b>'),
        type="string",
        name="P_V_C_ELEC",
      ),
      KML.SimpleField(
        KML.displayName('<b>VPH_AGUADV</b>'),
        type="string",
        name="VPH_AGUADV",
      ),
      KML.SimpleField(
        KML.displayName('<b>P_V_AGUADV</b>'),
        type="string",
        name="P_V_AGUADV",
      ),
      KML.SimpleField(
        KML.displayName('<b>VPH_DRENAJ</b>'),
        type="string",
        name="VPH_DRENAJ",
      ),
      KML.SimpleField(
        KML.displayName('<b>P_V_DRENAJ</b>'),
        type="string",
        name="P_V_DRENAJ",
      ),
      KML.SimpleField(
        KML.displayName('<b>VPH_EXCUSA</b>'),
        type="string",
        name="VPH_EXCUSA",
      ),
      KML.SimpleField(
        KML.displayName('<b>P_V_EXCUSA</b>'),
        type="string",
        name="P_V_EXCUSA",
      ),
      KML.SimpleField(
        KML.displayName('<b>V_3MASOCUP</b>'),
        type="string",
        name="V_3MASOCUP",
      ),
      KML.SimpleField(
        KML.displayName('<b>P_3MASOCUP</b>'),
        type="string",
        name="P_3MASOCUP",
      ),
      KML.SimpleField(
        KML.displayName('<b>PROOCUP_C</b>'),
        type="string",
        name="PROOCUP_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>POBTOT</b>'),
        type="string",
        name="POBTOT",
      ),
      KML.SimpleField(
        KML.displayName('<b>P0A14A</b>'),
        type="string",
        name="P0A14A",
      ),
      KML.SimpleField(
        KML.displayName('<b>PP0A14A</b>'),
        type="string",
        name="PP0A14A",
      ),
      KML.SimpleField(
        KML.displayName('<b>P15A29A</b>'),
        type="string",
        name="P15A29A",
      ),
      KML.SimpleField(
        KML.displayName('<b>PP15A29A</b>'),
        type="string",
        name="PP15A29A",
      ),
      KML.SimpleField(
        KML.displayName('<b>P30A59A</b>'),
        type="string",
        name="P30A59A",
      ),
      KML.SimpleField(
        KML.displayName('<b>PP30A59A</b>'),
        type="string",
        name="PP30A59A",
      ),
      KML.SimpleField(
        KML.displayName('<b>P_60YMAS</b>'),
        type="string",
        name="P_60YMAS",
      ),
      KML.SimpleField(
        KML.displayName('<b>PP_60YMAS</b>'),
        type="string",
        name="PP_60YMAS",
      ),
      KML.SimpleField(
        KML.displayName('<b>PCON_LIM</b>'),
        type="string",
        name="PCON_LIM",
      ),
      KML.SimpleField(
        KML.displayName('<b>PPCON_LIM</b>'),
        type="string",
        name="PPCON_LIM",
      ),
      KML.SimpleField(
        KML.displayName('<b>GRAPROES</b>'),
        type="string",
        name="GRAPROES",
      ),
      KML.SimpleField(
        KML.displayName('<b>ACESOPER_</b>'),
        type="string",
        name="ACESOPER_",
      ),
      KML.SimpleField(
        KML.displayName('<b>ACESOAUT_</b>'),
        type="string",
        name="ACESOAUT_",
      ),
      KML.SimpleField(
        KML.displayName('<b>RECUCALL_</b>'),
        type="string",
        name="RECUCALL_",
      ),
      KML.SimpleField(
        KML.displayName('<b>SENALIZA_</b>'),
        type="string",
        name="SENALIZA_",
      ),
      KML.SimpleField(
        KML.displayName('<b>ALUMPUB_</b>'),
        type="string",
        name="ALUMPUB_",
      ),
      KML.SimpleField(
        KML.displayName('<b>TELPUB_</b>'),
        type="string",
        name="TELPUB_",
      ),
      KML.SimpleField(
        KML.displayName('<b>BANQUETA_</b>'),
        type="string",
        name="BANQUETA_",
      ),
      KML.SimpleField(
        KML.displayName('<b>GUARNICI_</b>'),
        type="string",
        name="GUARNICI_",
      ),
      KML.SimpleField(
        KML.displayName('<b>ARBOLES_</b>'),
        type="string",
        name="ARBOLES_",
      ),
      KML.SimpleField(
        KML.displayName('<b>RAMPAS_</b>'),
        type="string",
        name="RAMPAS_",
      ),
      KML.SimpleField(
        KML.displayName('<b>PUESSEMI_</b>'),
        type="string",
        name="PUESSEMI_",
      ),
      KML.SimpleField(
        KML.displayName('<b>PUESAMBU_</b>'),
        type="string",
        name="PUESAMBU_",
      ),
      KML.SimpleField(
        KML.displayName('<b>ACESOPER_C</b>'),
        type="string",
        name="ACESOPER_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>ACESOAUT_C</b>'),
        type="string",
        name="ACESOAUT_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>RECUCALL_C</b>'),
        type="string",
        name="RECUCALL_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>SENALIZA_C</b>'),
        type="string",
        name="SENALIZA_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>ALUMPUB_C</b>'),
        type="string",
        name="ALUMPUB_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>TELPUB_C</b>'),
        type="string",
        name="TELPUB_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>BANQUETA_C</b>'),
        type="string",
        name="BANQUETA_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>GUARNICI_C</b>'),
        type="string",
        name="GUARNICI_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>ARBOLES_C</b>'),
        type="string",
        name="ARBOLES_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>RAMPAS_C</b>'),
        type="string",
        name="RAMPAS_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>PUESSEMI_C</b>'),
        type="string",
        name="PUESSEMI_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>PUESAMBU_C</b>'),
        type="string",
        name="PUESAMBU_C",
      ),
      KML.SimpleField(
        KML.displayName('<b>ENT</b>'),
        type="string",
        name="ENT",
      ),
      KML.SimpleField(
        KML.displayName('<b>NOM_ENT</b>'),
        type="string",
        name="NOM_ENT",
      ),
      KML.SimpleField(
        KML.displayName('<b>MUN</b>'),
        type="string",
        name="MUN",
      ),
      KML.SimpleField(
        KML.displayName('<b>NOM_MUN</b>'),
        type="string",
        name="NOM_MUN",
      ),
      KML.SimpleField(
        KML.displayName('<b>LOC</b>'),
        type="string",
        name="LOC",
      ),
      KML.SimpleField(
        KML.displayName('<b>NOM_LOC</b>'),
        type="string",
        name="NOM_LOC",
      ),
      KML.SimpleField(
        KML.displayName('<b>AGEB</b>'),
        type="string",
        name="AGEB",
      ),
      KML.SimpleField(
        KML.displayName('<b>MZA</b>'),
        type="string",
        name="MZA",
      ),
      KML.SimpleField(
        KML.displayName('<b>FECHA_POLI</b>'),
        type="string",
        name="FECHA_POLI",
      ),
      KML.SimpleField(
        KML.displayName('<b>FECHA_INF</b>'),
        type="string",
        name="FECHA_INF",
      ),
      KML.SimpleField(
        KML.displayName('<b>FECHA_CEU</b>'),
        type="string",
        name="FECHA_CEU",
      ),
      KML.SimpleField(
        KML.displayName('<b>OID</b>'),
        type="int",
        name="OID",
      ),
      name="28_Manzanas_INV2016",
      id="S_28_Manzanas_INV2016_SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSI",
    ),
    KML.Style(
      KML.BalloonStyle(
        KML.text(
'<table border="0"> '
  '<tr><td><b>CVEGEO</b></td><td>$[28_Manzanas_INV2016/CVEGEO]</td></tr> '
  '<tr><td><b>VIVTOT</b></td><td>$[28_Manzanas_INV2016/VIVTOT]</td></tr> '
  '<tr><td><b>TVIVHAB</b></td><td>$[28_Manzanas_INV2016/TVIVHAB]</td></tr> '
  '<tr><td><b>P_TVIVHAB</b></td><td>$[28_Manzanas_INV2016/P_TVIVHAB]</td></tr> '
  '<tr><td><b>TVIVPAR</b></td><td>$[28_Manzanas_INV2016/TVIVPAR]</td></tr> '
  '<tr><td><b>P_TVIVPAR</b></td><td>$[28_Manzanas_INV2016/P_TVIVPAR]</td></tr> '
  '<tr><td><b>TVIVPARHAB</b></td><td>$[28_Manzanas_INV2016/TVIVPARHAB]</td></tr> '
  '<tr><td><b>PVIVPARHAB</b></td><td>$[28_Manzanas_INV2016/PVIVPARHAB]</td></tr> '
  '<tr><td><b>VIVPAR_DES</b></td><td>$[28_Manzanas_INV2016/VIVPAR_DES]</td></tr> '
  '<tr><td><b>P_VIVPAR_D</b></td><td>$[28_Manzanas_INV2016/P_VIVPAR_D]</td></tr> '
  '<tr><td><b>VIVPAR_UT</b></td><td>$[28_Manzanas_INV2016/VIVPAR_UT]</td></tr> '
  '<tr><td><b>P_VIVPAR_U</b></td><td>$[28_Manzanas_INV2016/P_VIVPAR_U]</td></tr> '
  '<tr><td><b>VIVNOHAB</b></td><td>$[28_Manzanas_INV2016/VIVNOHAB]</td></tr> '
  '<tr><td><b>P_VIVNOHAB</b></td><td>$[28_Manzanas_INV2016/P_VIVNOHAB]</td></tr> '
  '<tr><td><b>VPH_PISODT</b></td><td>$[28_Manzanas_INV2016/VPH_PISODT]</td></tr> '
  '<tr><td><b>P_V_PISODT</b></td><td>$[28_Manzanas_INV2016/P_V_PISODT]</td></tr> '
  '<tr><td><b>VPH_C_ELEC</b></td><td>$[28_Manzanas_INV2016/VPH_C_ELEC]</td></tr> '
  '<tr><td><b>P_V_C_ELEC</b></td><td>$[28_Manzanas_INV2016/P_V_C_ELEC]</td></tr> '
  '<tr><td><b>VPH_AGUADV</b></td><td>$[28_Manzanas_INV2016/VPH_AGUADV]</td></tr> '
  '<tr><td><b>P_V_AGUADV</b></td><td>$[28_Manzanas_INV2016/P_V_AGUADV]</td></tr> '
  '<tr><td><b>VPH_DRENAJ</b></td><td>$[28_Manzanas_INV2016/VPH_DRENAJ]</td></tr> '
  '<tr><td><b>P_V_DRENAJ</b></td><td>$[28_Manzanas_INV2016/P_V_DRENAJ]</td></tr> '
  '<tr><td><b>VPH_EXCUSA</b></td><td>$[28_Manzanas_INV2016/VPH_EXCUSA]</td></tr> '
  '<tr><td><b>P_V_EXCUSA</b></td><td>$[28_Manzanas_INV2016/P_V_EXCUSA]</td></tr> '
  '<tr><td><b>V_3MASOCUP</b></td><td>$[28_Manzanas_INV2016/V_3MASOCUP]</td></tr> '
  '<tr><td><b>P_3MASOCUP</b></td><td>$[28_Manzanas_INV2016/P_3MASOCUP]</td></tr> '
  '<tr><td><b>PROOCUP_C</b></td><td>$[28_Manzanas_INV2016/PROOCUP_C]</td></tr> '
  '<tr><td><b>POBTOT</b></td><td>$[28_Manzanas_INV2016/POBTOT]</td></tr> '
  '<tr><td><b>P0A14A</b></td><td>$[28_Manzanas_INV2016/P0A14A]</td></tr> '
  '<tr><td><b>PP0A14A</b></td><td>$[28_Manzanas_INV2016/PP0A14A]</td></tr> '
  '<tr><td><b>P15A29A</b></td><td>$[28_Manzanas_INV2016/P15A29A]</td></tr> '
  '<tr><td><b>PP15A29A</b></td><td>$[28_Manzanas_INV2016/PP15A29A]</td></tr> '
  '<tr><td><b>P30A59A</b></td><td>$[28_Manzanas_INV2016/P30A59A]</td></tr> '
  '<tr><td><b>PP30A59A</b></td><td>$[28_Manzanas_INV2016/PP30A59A]</td></tr> '
  '<tr><td><b>P_60YMAS</b></td><td>$[28_Manzanas_INV2016/P_60YMAS]</td></tr> '
  '<tr><td><b>PP_60YMAS</b></td><td>$[28_Manzanas_INV2016/PP_60YMAS]</td></tr> '
  '<tr><td><b>PCON_LIM</b></td><td>$[28_Manzanas_INV2016/PCON_LIM]</td></tr> '
  '<tr><td><b>PPCON_LIM</b></td><td>$[28_Manzanas_INV2016/PPCON_LIM]</td></tr> '
  '<tr><td><b>GRAPROES</b></td><td>$[28_Manzanas_INV2016/GRAPROES]</td></tr> '
  '<tr><td><b>ACESOPER_</b></td><td>$[28_Manzanas_INV2016/ACESOPER_]</td></tr> '
  '<tr><td><b>ACESOAUT_</b></td><td>$[28_Manzanas_INV2016/ACESOAUT_]</td></tr> '
  '<tr><td><b>RECUCALL_</b></td><td>$[28_Manzanas_INV2016/RECUCALL_]</td></tr> '
  '<tr><td><b>SENALIZA_</b></td><td>$[28_Manzanas_INV2016/SENALIZA_]</td></tr> '
  '<tr><td><b>ALUMPUB_</b></td><td>$[28_Manzanas_INV2016/ALUMPUB_]</td></tr> '
  '<tr><td><b>TELPUB_</b></td><td>$[28_Manzanas_INV2016/TELPUB_]</td></tr> '
  '<tr><td><b>BANQUETA_</b></td><td>$[28_Manzanas_INV2016/BANQUETA_]</td></tr> '
  '<tr><td><b>GUARNICI_</b></td><td>$[28_Manzanas_INV2016/GUARNICI_]</td></tr> '
  '<tr><td><b>ARBOLES_</b></td><td>$[28_Manzanas_INV2016/ARBOLES_]</td></tr> '
  '<tr><td><b>RAMPAS_</b></td><td>$[28_Manzanas_INV2016/RAMPAS_]</td></tr> '
  '<tr><td><b>PUESSEMI_</b></td><td>$[28_Manzanas_INV2016/PUESSEMI_]</td></tr> '
  '<tr><td><b>PUESAMBU_</b></td><td>$[28_Manzanas_INV2016/PUESAMBU_]</td></tr> '
  '<tr><td><b>ACESOPER_C</b></td><td>$[28_Manzanas_INV2016/ACESOPER_C]</td></tr> '
  '<tr><td><b>ACESOAUT_C</b></td><td>$[28_Manzanas_INV2016/ACESOAUT_C]</td></tr> '
  '<tr><td><b>RECUCALL_C</b></td><td>$[28_Manzanas_INV2016/RECUCALL_C]</td></tr> '
  '<tr><td><b>SENALIZA_C</b></td><td>$[28_Manzanas_INV2016/SENALIZA_C]</td></tr> '
  '<tr><td><b>ALUMPUB_C</b></td><td>$[28_Manzanas_INV2016/ALUMPUB_C]</td></tr> '
  '<tr><td><b>TELPUB_C</b></td><td>$[28_Manzanas_INV2016/TELPUB_C]</td></tr> '
  '<tr><td><b>BANQUETA_C</b></td><td>$[28_Manzanas_INV2016/BANQUETA_C]</td></tr> '
  '<tr><td><b>GUARNICI_C</b></td><td>$[28_Manzanas_INV2016/GUARNICI_C]</td></tr> '
  '<tr><td><b>ARBOLES_C</b></td><td>$[28_Manzanas_INV2016/ARBOLES_C]</td></tr> '
  '<tr><td><b>RAMPAS_C</b></td><td>$[28_Manzanas_INV2016/RAMPAS_C]</td></tr> '
  '<tr><td><b>PUESSEMI_C</b></td><td>$[28_Manzanas_INV2016/PUESSEMI_C]</td></tr> '
  '<tr><td><b>PUESAMBU_C</b></td><td>$[28_Manzanas_INV2016/PUESAMBU_C]</td></tr> '
  '<tr><td><b>ENT</b></td><td>$[28_Manzanas_INV2016/ENT]</td></tr> '
  '<tr><td><b>NOM_ENT</b></td><td>$[28_Manzanas_INV2016/NOM_ENT]</td></tr> '
  '<tr><td><b>MUN</b></td><td>$[28_Manzanas_INV2016/MUN]</td></tr> '
  '<tr><td><b>NOM_MUN</b></td><td>$[28_Manzanas_INV2016/NOM_MUN]</td></tr> '
  '<tr><td><b>LOC</b></td><td>$[28_Manzanas_INV2016/LOC]</td></tr> '
  '<tr><td><b>NOM_LOC</b></td><td>$[28_Manzanas_INV2016/NOM_LOC]</td></tr> '
  '<tr><td><b>AGEB</b></td><td>$[28_Manzanas_INV2016/AGEB]</td></tr> '
  '<tr><td><b>MZA</b></td><td>$[28_Manzanas_INV2016/MZA]</td></tr> '
  '<tr><td><b>FECHA_POLI</b></td><td>$[28_Manzanas_INV2016/FECHA_POLI]</td></tr> '
  '<tr><td><b>FECHA_INF</b></td><td>$[28_Manzanas_INV2016/FECHA_INF]</td></tr> '
  '<tr><td><b>FECHA_CEU</b></td><td>$[28_Manzanas_INV2016/FECHA_CEU]</td></tr> '
  '<tr><td><b>OID</b></td><td>$[28_Manzanas_INV2016/OID]</td></tr> '
'</table> '
        ),
      ),
      KML.PolyStyle(
        KML.colorMode('random'),
      ),
      id="falseColor",
    ),
    KML.Folder(
      KML.name('28_Manzanas_INV2016'),
      KML.Placemark(
        KML.styleUrl('#falseColor'),
        KML.Style(
          KML.IconStyle(
            KML.color('ffededed'),
            KML.colorMode('normal'),
          ),
          KML.LineStyle(
            KML.color('ffededed'),
            KML.colorMode('normal'),
          ),
          KML.PolyStyle(
            KML.color('ffededed'),
            KML.colorMode('normal'),
          ),
          id="inline",
        ),
        KML.ExtendedData(
          KML.SchemaData(
            KML.SimpleData('2800100010177001'  name="CVEGEO",
),
            KML.SimpleData('17'  name="VIVTOT",
),
            KML.SimpleData('11'  name="TVIVHAB",
),
            KML.SimpleData('64.71'  name="P_TVIVHAB",
),
            KML.SimpleData('17'  name="TVIVPAR",
),
            KML.SimpleData('100.00'  name="P_TVIVPAR",
),
            KML.SimpleData('11'  name="TVIVPARHAB",
),
            KML.SimpleData('64.71'  name="PVIVPARHAB",
),
            KML.SimpleData('4'  name="VIVPAR_DES",
),
            KML.SimpleData('23.53'  name="P_VIVPAR_D",
),
            KML.SimpleData('*'  name="VIVPAR_UT",
),
            KML.SimpleData('*'  name="P_VIVPAR_U",
),
            KML.SimpleData('6'  name="VIVNOHAB",
),
            KML.SimpleData('35.29'  name="P_VIVNOHAB",
),
            KML.SimpleData('11'  name="VPH_PISODT",
),
            KML.SimpleData('100.00'  name="P_V_PISODT",
),
            KML.SimpleData('11'  name="VPH_C_ELEC",
),
            KML.SimpleData('100.00'  name="P_V_C_ELEC",
),
            KML.SimpleData('10'  name="VPH_AGUADV",
),
            KML.SimpleData('90.91'  name="P_V_AGUADV",
),
            KML.SimpleData('10'  name="VPH_DRENAJ",
),
            KML.SimpleData('90.91'  name="P_V_DRENAJ",
),
            KML.SimpleData('11'  name="VPH_EXCUSA",
),
            KML.SimpleData('100.00'  name="P_V_EXCUSA",
),
            KML.SimpleData('0'  name="V_3MASOCUP",
),
            KML.SimpleData('0.00'  name="P_3MASOCUP",
),
            KML.SimpleData('3.27'  name="PROOCUP_C",
),
            KML.SimpleData('36'  name="POBTOT",
),
            KML.SimpleData('10'  name="P0A14A",
),
            KML.SimpleData('27.78'  name="PP0A14A",
),
            KML.SimpleData('6'  name="P15A29A",
),
            KML.SimpleData('16.67'  name="PP15A29A",
),
            KML.SimpleData('14'  name="P30A59A",
),
            KML.SimpleData('38.89'  name="PP30A59A",
),
            KML.SimpleData('6'  name="P_60YMAS",
),
            KML.SimpleData('16.67'  name="PP_60YMAS",
),
            KML.SimpleData('N.D.'  name="PCON_LIM",
),
            KML.SimpleData('N.D.'  name="PPCON_LIM",
),
            KML.SimpleData('8.36'  name="GRAPROES",
),
            KML.SimpleData('3'  name="ACESOPER_",
),
            KML.SimpleData('3'  name="ACESOAUT_",
),
            KML.SimpleData('2'  name="RECUCALL_",
),
            KML.SimpleData('3'  name="SENALIZA_",
),
            KML.SimpleData('1'  name="ALUMPUB_",
),
            KML.SimpleData('3'  name="TELPUB_",
),
            KML.SimpleData('1'  name="BANQUETA_",
),
            KML.SimpleData('1'  name="GUARNICI_",
),
            KML.SimpleData('3'  name="ARBOLES_",
),
            KML.SimpleData('3'  name="RAMPAS_",
),
            KML.SimpleData('3'  name="PUESSEMI_",
),
            KML.SimpleData('3'  name="PUESAMBU_",
),
            KML.SimpleData(u'Restricci\xf3n en ninguna vialidad'  name="ACESOPER_C",
),
            KML.SimpleData(u'Restricci\xf3n en ninguna vialidad'  name="ACESOAUT_C",
),
            KML.SimpleData('Alguna vialidad'  name="RECUCALL_C",
),
            KML.SimpleData('Ninguna vialidad'  name="SENALIZA_C",
),
            KML.SimpleData('Todas las vialidades'  name="ALUMPUB_C",
),
            KML.SimpleData('Ninguna vialidad'  name="TELPUB_C",
),
            KML.SimpleData('Todas las vialidades'  name="BANQUETA_C",
),
            KML.SimpleData('Todas las vialidades'  name="GUARNICI_C",
),
            KML.SimpleData('Ninguna vialidad'  name="ARBOLES_C",
),
            KML.SimpleData('Ninguna vialidad'  name="RAMPAS_C",
),
            KML.SimpleData('Ninguna vialidad'  name="PUESSEMI_C",
),
            KML.SimpleData('Ninguna vialidad'  name="PUESAMBU_C",
),
            KML.SimpleData('28'  name="ENT",
),
            KML.SimpleData('Tamaulipas'  name="NOM_ENT",
),
            KML.SimpleData('001'  name="MUN",
),
            KML.SimpleData('Abasolo'  name="NOM_MUN",
),
            KML.SimpleData('0001'  name="LOC",
),
            KML.SimpleData('Abasolo'  name="NOM_LOC",
),
            KML.SimpleData('0177'  name="AGEB",
),
            KML.SimpleData('001'  name="MZA",
),
            KML.SimpleData('2010'  name="FECHA_POLI",
),
            KML.SimpleData('2015'  name="FECHA_INF",
),
            KML.SimpleData('2014'  name="FECHA_CEU",
),
            KML.SimpleData('1'  name="OID",
),
            schemaUrl="#S_28_Manzanas_INV2016_SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSI",
          ),
        ),
        KML.Polygon(
          KML.outerBoundaryIs(
            KML.LinearRing(
              KML.coordinates(
       '-98.39363282999999,24.06603868999927,0 -98.39372682,24.06538037999928,0 -98.39219147999999,24.06519313999929,0 -98.39209443,24.06585051999921,0 -98.39363282999999,24.06603868999927,0 '
              ),
            ),
          ),
        ),
      ),
      KML.Placemark(
        KML.styleUrl('#falseColor'),
        KML.Style(
          KML.IconStyle(
            KML.color('ffededed'),
            KML.colorMode('normal'),
          ),
          KML.LineStyle(
            KML.color('ffededed'),
            KML.colorMode('normal'),
          ),
          KML.PolyStyle(
            KML.color('ffededed'),
            KML.colorMode('normal'),
          ),
          id="inline",
        ),
        KML.ExtendedData(
          KML.SchemaData(
            KML.SimpleData('2800100010177002'  name="CVEGEO",
),
            KML.SimpleData('0'  name="VIVTOT",
),
            KML.SimpleData('0'  name="TVIVHAB",
),
            KML.SimpleData('0.00'  name="P_TVIVHAB",
),
            KML.SimpleData('0'  name="TVIVPAR",
),
            KML.SimpleData('0.00'  name="P_TVIVPAR",
),
            KML.SimpleData('0'  name="TVIVPARHAB",
),
            KML.SimpleData('0.00'  name="PVIVPARHAB",
),
            KML.SimpleData('0'  name="VIVPAR_DES",
),
            KML.SimpleData('0.00'  name="P_VIVPAR_D",
),
            KML.SimpleData('0'  name="VIVPAR_UT",
),
            KML.SimpleData('0.00'  name="P_VIVPAR_U",
),
            KML.SimpleData('0'  name="VIVNOHAB",
),
            KML.SimpleData('0.00'  name="P_VIVNOHAB",
),
            KML.SimpleData('N.D.'  name="VPH_PISODT",
),
            KML.SimpleData('N.D.'  name="P_V_PISODT",
),
            KML.SimpleData('N.D.'  name="VPH_C_ELEC",
),
            KML.SimpleData('N.D.'  name="P_V_C_ELEC",
),
            KML.SimpleData('N.D.'  name="VPH_AGUADV",
),
            KML.SimpleData('N.D.'  name="P_V_AGUADV",
),
            KML.SimpleData('N.D.'  name="VPH_DRENAJ",
),
            KML.SimpleData('N.D.'  name="P_V_DRENAJ",
),
            KML.SimpleData('N.D.'  name="VPH_EXCUSA",
),
            KML.SimpleData('N.D.'  name="P_V_EXCUSA",
),
            KML.SimpleData('N.D.'  name="V_3MASOCUP",
),
            KML.SimpleData('N.D.'  name="P_3MASOCUP",
),
            KML.SimpleData('N.D.'  name="PROOCUP_C",
),
            KML.SimpleData('N.D.'  name="POBTOT",
),
            KML.SimpleData('N.D.'  name="P0A14A",
),
            KML.SimpleData('N.D.'  name="PP0A14A",
),
            KML.SimpleData('N.D.'  name="P15A29A",
),
            KML.SimpleData('N.D.'  name="PP15A29A",
),
            KML.SimpleData('N.D.'  name="P30A59A",
),
            KML.SimpleData('N.D.'  name="PP30A59A",
),
            KML.SimpleData('N.D.'  name="P_60YMAS",
),
            KML.SimpleData('N.D.'  name="PP_60YMAS",
),
            KML.SimpleData('N.D.'  name="PCON_LIM",
),
            KML.SimpleData('N.D.'  name="PPCON_LIM",
),
            KML.SimpleData('N.D.'  name="GRAPROES",
),
            KML.SimpleData('3'  name="ACESOPER_",
),
            KML.SimpleData('3'  name="ACESOAUT_",
),
            KML.SimpleData('1'  name="RECUCALL_",
),
            KML.SimpleData('3'  name="SENALIZA_",
),
            KML.SimpleData('1'  name="ALUMPUB_",
),
            KML.SimpleData('3'  name="TELPUB_",
),
            KML.SimpleData('1'  name="BANQUETA_",
),
            KML.SimpleData('1'  name="GUARNICI_",
),
            KML.SimpleData('3'  name="ARBOLES_",
),
            KML.SimpleData('3'  name="RAMPAS_",
),
            KML.SimpleData('3'  name="PUESSEMI_",
),
            KML.SimpleData('3'  name="PUESAMBU_",
),
            KML.SimpleData(u'Restricci\xf3n en ninguna vialidad'  name="ACESOPER_C",
),
            KML.SimpleData(u'Restricci\xf3n en ninguna vialidad'  name="ACESOAUT_C",
),
            KML.SimpleData('Todas las vialidades'  name="RECUCALL_C",
),
            KML.SimpleData('Ninguna vialidad'  name="SENALIZA_C",
),
            KML.SimpleData('Todas las vialidades'  name="ALUMPUB_C",
),
            KML.SimpleData('Ninguna vialidad'  name="TELPUB_C",
),
            KML.SimpleData('Todas las vialidades'  name="BANQUETA_C",
),
            KML.SimpleData('Todas las vialidades'  name="GUARNICI_C",
),
            KML.SimpleData('Ninguna vialidad'  name="ARBOLES_C",
),
            KML.SimpleData('Ninguna vialidad'  name="RAMPAS_C",
),
            KML.SimpleData('Ninguna vialidad'  name="PUESSEMI_C",
),
            KML.SimpleData('Ninguna vialidad'  name="PUESAMBU_C",
),
            KML.SimpleData('28'  name="ENT",
),
            KML.SimpleData('Tamaulipas'  name="NOM_ENT",
),
            KML.SimpleData('001'  name="MUN",
),
            KML.SimpleData('Abasolo'  name="NOM_MUN",
),
            KML.SimpleData('0001'  name="LOC",
),
            KML.SimpleData('Abasolo'  name="NOM_LOC",
),
            KML.SimpleData('0177'  name="AGEB",
),
            KML.SimpleData('002'  name="MZA",
),
            KML.SimpleData('2010'  name="FECHA_POLI",
),
            KML.SimpleData('2015'  name="FECHA_INF",
),
            KML.SimpleData('2014'  name="FECHA_CEU",
),
            KML.SimpleData('2'  name="OID",
),
            schemaUrl="#S_28_Manzanas_INV2016_SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSI",
          ),
        ),
        KML.Polygon(
          KML.outerBoundaryIs(
            KML.LinearRing(
              KML.coordinates(
       '-98.39199176999998,24.06583796999929,0 -98.39206773999999,24.06531187999929,0 -98.39208672000001,24.06518034999932,0 -98.39159105999998,24.06511988999931,0 -98.3910954,24.0650594299993,0 -98.39059971999998,24.06499896999929,0 -98.3905032,24.06565585999929,0 -98.39199176999998,24.06583796999929,0 '
              ),
            ),
          ),
        ),
      ),
      KML.Placemark(
        KML.styleUrl('#falseColor'),
        KML.Style(
          KML.IconStyle(
            KML.color('ffededed'),
            KML.colorMode('normal'),
          ),
          KML.LineStyle(
            KML.color('ffededed'),
            KML.colorMode('normal'),
          ),
          KML.PolyStyle(
            KML.color('ffededed'),
            KML.colorMode('normal'),
          ),
          id="inline",
        ),
        KML.ExtendedData(
          KML.SchemaData(
            KML.SimpleData('2800100010177003'  name="CVEGEO",
),
            KML.SimpleData('0'  name="VIVTOT",
),
            KML.SimpleData('0'  name="TVIVHAB",
),
            KML.SimpleData('0.00'  name="P_TVIVHAB",
),
            KML.SimpleData('0'  name="TVIVPAR",
),
            KML.SimpleData('0.00'  name="P_TVIVPAR",
),
            KML.SimpleData('0'  name="TVIVPARHAB",
),
            KML.SimpleData('0.00'  name="PVIVPARHAB",
),
            KML.SimpleData('0'  name="VIVPAR_DES",
),
            KML.SimpleData('0.00'  name="P_VIVPAR_D",
),
            KML.SimpleData('0'  name="VIVPAR_UT",
),
            KML.SimpleData('0.00'  name="P_VIVPAR_U",
),
            KML.SimpleData('0'  name="VIVNOHAB",
),
            KML.SimpleData('0.00'  name="P_VIVNOHAB",
),
            KML.SimpleData('N.D.'  name="VPH_PISODT",
),
            KML.SimpleData('N.D.'  name="P_V_PISODT",
),
            KML.SimpleData('N.D.'  name="VPH_C_ELEC",
),
            KML.SimpleData('N.D.'  name="P_V_C_ELEC",
),
            KML.SimpleData('N.D.'  name="VPH_AGUADV",
),
            KML.SimpleData('N.D.'  name="P_V_AGUADV",
),
            KML.SimpleData('N.D.'  name="VPH_DRENAJ",
),
            KML.SimpleData('N.D.'  name="P_V_DRENAJ",
),
            KML.SimpleData('N.D.'  name="VPH_EXCUSA",
),
            KML.SimpleData('N.D.'  name="P_V_EXCUSA",
),
            KML.SimpleData('N.D.'  name="V_3MASOCUP",
),
            KML.SimpleData('N.D.'  name="P_3MASOCUP",
),
            KML.SimpleData('N.D.'  name="PROOCUP_C",
),
            KML.SimpleData('N.D.'  name="POBTOT",
),
            KML.SimpleData('N.D.'  name="P0A14A",
),
            KML.SimpleData('N.D.'  name="PP0A14A",
),
            KML.SimpleData('N.D.'  name="P15A29A",
),
            KML.SimpleData('N.D.'  name="PP15A29A",
),
            KML.SimpleData('N.D.'  name="P30A59A",
),
            KML.SimpleData('N.D.'  name="PP30A59A",
),
            KML.SimpleData('N.D.'  name="P_60YMAS",
),
            KML.SimpleData('N.D.'  name="PP_60YMAS",
),
            KML.SimpleData('N.D.'  name="PCON_LIM",
),
            KML.SimpleData('N.D.'  name="PPCON_LIM",
),
            KML.SimpleData('N.D.'  name="GRAPROES",
),
            KML.SimpleData('3'  name="ACESOPER_",
),
            KML.SimpleData('3'  name="ACESOAUT_",
),
            KML.SimpleData('1'  name="RECUCALL_",
),
            KML.SimpleData('3'  name="SENALIZA_",
),
            KML.SimpleData('1'  name="ALUMPUB_",
),
            KML.SimpleData('3'  name="TELPUB_",
),
            KML.SimpleData('1'  name="BANQUETA_",
),
            KML.SimpleData('1'  name="GUARNICI_",
),
            KML.SimpleData('2'  name="ARBOLES_",
),
            KML.SimpleData('3'  name="RAMPAS_",
),
            KML.SimpleData('3'  name="PUESSEMI_",
),
            KML.SimpleData('3'  name="PUESAMBU_",
),
            KML.SimpleData(u'Restricci\xf3n en ninguna vialidad'  name="ACESOPER_C",
),
            KML.SimpleData(u'Restricci\xf3n en ninguna vialidad'  name="ACESOAUT_C",
),
            KML.SimpleData('Todas las vialidades'  name="RECUCALL_C",
),
            KML.SimpleData('Ninguna vialidad'  name="SENALIZA_C",
),
            KML.SimpleData('Todas las vialidades'  name="ALUMPUB_C",
),
            KML.SimpleData('Ninguna vialidad'  name="TELPUB_C",
),
            KML.SimpleData('Todas las vialidades'  name="BANQUETA_C",
),
            KML.SimpleData('Todas las vialidades'  name="GUARNICI_C",
),
            KML.SimpleData('Alguna vialidad'  name="ARBOLES_C",
),
            KML.SimpleData('Ninguna vialidad'  name="RAMPAS_C",
),
            KML.SimpleData('Ninguna vialidad'  name="PUESSEMI_C",
),
            KML.SimpleData('Ninguna vialidad'  name="PUESAMBU_C",
),
            KML.SimpleData('28'  name="ENT",
),
            KML.SimpleData('Tamaulipas'  name="NOM_ENT",
),
            KML.SimpleData('001'  name="MUN",
),
            KML.SimpleData('Abasolo'  name="NOM_MUN",
),
            KML.SimpleData('0001'  name="LOC",
),
            KML.SimpleData('Abasolo'  name="NOM_LOC",
),
            KML.SimpleData('0177'  name="AGEB",
),
            KML.SimpleData('003'  name="MZA",
),
            KML.SimpleData('2010'  name="FECHA_POLI",
),
            KML.SimpleData('2015'  name="FECHA_INF",
),
            KML.SimpleData('2014'  name="FECHA_CEU",
),
            KML.SimpleData('3'  name="OID",
),
            schemaUrl="#S_28_Manzanas_INV2016_SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSI",
          ),
        ),
        KML.Polygon(
          KML.outerBoundaryIs(
            KML.LinearRing(
              KML.coordinates(
       '-98.39061777000001,24.06487610999928,0 -98.39136112,24.06496676999931,0 -98.39210448,24.0650574299993,0 -98.39219897,24.06440305999931,0 -98.39071391,24.06422177999922,0 -98.39061777000001,24.06487610999928,0 '
              ),
            ),
          ),
        ),
      ),
      KML.Placemark(
        KML.styleUrl('#falseColor'),
        KML.Style(
          KML.IconStyle(
            KML.color('ffededed'),
            KML.colorMode('normal'),
          ),
          KML.LineStyle(
            KML.color('ffededed'),
            KML.colorMode('normal'),
          ),
          KML.PolyStyle(
            KML.color('ffededed'),
            KML.colorMode('normal'),
          ),
          id="inline",
        ),
        KML.ExtendedData(
          KML.SchemaData(
            KML.SimpleData('2800100010177004'  name="CVEGEO",
),
            KML.SimpleData('16'  name="VIVTOT",
),
            KML.SimpleData('7'  name="TVIVHAB",
),
            KML.SimpleData('43.75'  name="P_TVIVHAB",
),
            KML.SimpleData('16'  name="TVIVPAR",
),
            KML.SimpleData('100.00'  name="P_TVIVPAR",
),
            KML.SimpleData('7'  name="TVIVPARHAB",
),
            KML.SimpleData('43.75'  name="PVIVPARHAB",
),
            KML.SimpleData('8'  name="VIVPAR_DES",
),
            KML.SimpleData('50.00'  name="P_VIVPAR_D",
),
            KML.SimpleData('*'  name="VIVPAR_UT",
),
            KML.SimpleData('*'  name="P_VIVPAR_U",
),
            KML.SimpleData('9'  name="VIVNOHAB",
),
            KML.SimpleData('56.25'  name="P_VIVNOHAB",
),
            KML.SimpleData('7'  name="VPH_PISODT",
),
            KML.SimpleData('100.00'  name="P_V_PISODT",
),
            KML.SimpleData('7'  name="VPH_C_ELEC",
),
            KML.SimpleData('100.00'  name="P_V_C_ELEC",
),
            KML.SimpleData('7'  name="VPH_AGUADV",
),
            KML.SimpleData('100.00'  name="P_V_AGUADV",
),
            KML.SimpleData('7'  name="VPH_DRENAJ",
),
            KML.SimpleData('100.00'  name="P_V_DRENAJ",
),
            KML.SimpleData('7'  name="VPH_EXCUSA",
),
            KML.SimpleData('100.00'  name="P_V_EXCUSA",
),
            KML.SimpleData('0'  name="V_3MASOCUP",
),
            KML.SimpleData('0.00'  name="P_3MASOCUP",
),
            KML.SimpleData('2.57'  name="PROOCUP_C",
),
            KML.SimpleData('18'  name="POBTOT",
),
            KML.SimpleData('5'  name="P0A14A",
),
            KML.SimpleData('27.78'  name="PP0A14A",
),
            KML.SimpleData('3'  name="P15A29A",
),
            KML.SimpleData('16.67'  name="PP15A29A",
),
            KML.SimpleData('7'  name="P30A59A",
),
            KML.SimpleData('38.89'  name="PP30A59A",
),
            KML.SimpleData('3'  name="P_60YMAS",
),
            KML.SimpleData('16.67'  name="PP_60YMAS",
),
            KML.SimpleData('N.D.'  name="PCON_LIM",
),
            KML.SimpleData('N.D.'  name="PPCON_LIM",
),
            KML.SimpleData('9.91'  name="GRAPROES",
),
            KML.SimpleData('3'  name="ACESOPER_",
),
            KML.SimpleData('3'  name="ACESOAUT_",
),
            KML.SimpleData('1'  name="RECUCALL_",
),
            KML.SimpleData('3'  name="SENALIZA_",
),
            KML.SimpleData('1'  name="ALUMPUB_",
),
            KML.SimpleData('3'  name="TELPUB_",
),
            KML.SimpleData('1'  name="BANQUETA_",
),
            KML.SimpleData('1'  name="GUARNICI_",
),
            KML.SimpleData('2'  name="ARBOLES_",
),
            KML.SimpleData('3'  name="RAMPAS_",
),
            KML.SimpleData('3'  name="PUESSEMI_",
),
            KML.SimpleData('3'  name="PUESAMBU_",
),
            KML.SimpleData(u'Restricci\xf3n en ninguna vialidad'  name="ACESOPER_C",
),
            KML.SimpleData(u'Restricci\xf3n en ninguna vialidad'  name="ACESOAUT_C",
),
            KML.SimpleData('Todas las vialidades'  name="RECUCALL_C",
),
            KML.SimpleData('Ninguna vialidad'  name="SENALIZA_C",
),
            KML.SimpleData('Todas las vialidades'  name="ALUMPUB_C",
),
            KML.SimpleData('Ninguna vialidad'  name="TELPUB_C",
),
            KML.SimpleData('Todas las vialidades'  name="BANQUETA_C",
),
            KML.SimpleData('Todas las vialidades'  name="GUARNICI_C",
),
            KML.SimpleData('Alguna vialidad'  name="ARBOLES_C",
),
            KML.SimpleData('Ninguna vialidad'  name="RAMPAS_C",
),
            KML.SimpleData('Ninguna vialidad'  name="PUESSEMI_C",
),
            KML.SimpleData('Ninguna vialidad'  name="PUESAMBU_C",
),
            KML.SimpleData('28'  name="ENT",
),
            KML.SimpleData('Tamaulipas'  name="NOM_ENT",
),
            KML.SimpleData('001'  name="MUN",
),
            KML.SimpleData('Abasolo'  name="NOM_MUN",
),
            KML.SimpleData('0001'  name="LOC",
),
            KML.SimpleData('Abasolo'  name="NOM_LOC",
),
            KML.SimpleData('0177'  name="AGEB",
),
            KML.SimpleData('004'  name="MZA",
),
            KML.SimpleData('2010'  name="FECHA_POLI",
),
            KML.SimpleData('2015'  name="FECHA_INF",
),
            KML.SimpleData('2014'  name="FECHA_CEU",
),
            KML.SimpleData('4'  name="OID",
),
            schemaUrl="#S_28_Manzanas_INV2016_SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSI",
          ),
        ),
        KML.Polygon(
          KML.outerBoundaryIs(
            KML.LinearRing(
              KML.coordinates(
       '-98.39220962,24.06507027999932,0 -98.39374436999999,24.0652574499993,0 -98.39383778,24.06460310999932,0 -98.39230618000002,24.06441614999927,0 -98.39220962,24.06507027999932,0 '
              ),
            ),
          ),
        ),
      ),
      id="layer 0",
    ),
  ),
)
print etree.tostring(etree.ElementTree(doc),pretty_print=True)

